public enum CardType
{
    Graduate,
    AdderalSupply,
    Kuda,
    Breadcrumbs,
    KudaWithTheLads,
    BreadcrumbFactory,
    FirstYearInTheLibrary,
    NightBeforeExams,
    ArguingOverBars,
    BadIntentionsSTYC,
    Resits,
    IndustrialAction,
    Hangover,
    SummerBreak,
    CopyNotes,
    ChristianUnionLeaflet,
    DropOut,
    StudentDebt
}
